### ISSUE TITLE
nmap在kali里面指定了目录但是显示未启用插件。。。

### ISSUE THREAD

**Issue by dockernes** [iSafeBlue/TrackRay#1]
nmap在kali里面指定了目录但是显示未启用插件。。。

**Comment by iSafeBlue** [comment]
你可能是通过接口去调用了 "NMAP" 这个插件，因为这个插件在 `@Rule` 注解中配置 enable 为 false，所以该插件不能被外部所调用，他是在程序内部中才可以被调用的，你可以通过 /scan 扫描功能中勾选 `端口扫描`来调用 nmap 插件对目标进行端口扫描。

如果以上不是你想要的答案，请附上详细的操作描述和截图。
