### ISSUE TITLE
下载的已编译版，运行完trackray.jar后，访问不了web页面！！

### ISSUE THREAD

**Issue by Feng4** [iSafeBlue/TrackRay#17]
![image](https://user-images.githubusercontent.com/27730186/63324464-b7d25a80-c35a-11e9-9794-c2f07c99d00d.png)
有几个error。

**Comment by iSafeBlue** [comment]
MSF没有配置正确，不影响程序的启动和使用
如没有其他异常是可以正常访问本地 8080 端口的
你可以用 netstat 命令查看端口启用状态
