### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xMario0** [iSafeBlue/TrackRay#27]
***************************
APPLICATION FAILED TO START
***************************

Description:

Field pluginPool in com.trackray.web.service.impl.PluginServiceImpl required a bean of type 'java.util.concurrent.ConcurrentHashMap' that could not be found.

The injection point has the following annotations:
        - @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'java.util.concurrent.ConcurrentHashMap' in your configuration.

**Comment by iSafeBlue** [comment]
看一下你的jdk版本是不是1.8不是就换成1.8

**Comment by xMario0** [comment]
thanks
