### ISSUE TITLE
Error: Unable to access jarfile trackray.jar

### ISSUE THREAD

**Issue by safebaseline** [iSafeBlue/TrackRay#4]
trackray.jar
![image](https://user-images.githubusercontent.com/38883009/57963640-eb67a800-7959-11e9-9773-f5bdc698ceaf.png)

**Comment by iSafeBlue** [comment]
你描述的问题太简单，根本没有明白你在遇到问题之前做了那些操作，所以我也只能给你一个简单的回复。
1.检查是否为trackray工作目录。
2.有没有按照我给出的安装流程安装
3.是否通过 maven 成功编译项目并生成了 trackray.jar
4.检查目录下是否有 trackray.jar

**Comment by safebaseline** [comment]
![image](https://user-images.githubusercontent.com/38883009/57964971-3a203c80-7970-11e9-9387-32d2841573cc.png)
编译出错
![image](https://user-images.githubusercontent.com/38883009/57964983-545a1a80-7970-11e9-9566-22248a51e0c3.png)
java装了

**Comment by CaledoniaProject** [comment]
你装的JRE，得用JDK吧，ERROR里说了

**Comment by safebaseline** [comment]
好的 多谢大佬！我卸掉重试下！


 
---Original---
