### ISSUE TITLE
关于awvs等一些we内

### ISSUE THREAD

**Issue by just805** [iSafeBlue/TrackRay#5]
首先感谢你的项目，今天我在虚拟机测试了一下，发现如下问题。
1、物理安装了awvs无法在虚拟机中访问。
2、msfconsole 默认pass user 都是msf,且连接失败。

建议公众开放一个QQ群或其他方便用户讨论。

**Comment by iSafeBlue** [comment]
1.在虚拟机中访问一下物理机的awvs地址，确保可以正常通信，然后修改 application.properties 配置文件中对应的参数。
2. msf 需要你先启动 msfrpc，我文档中已经给出如何启动 msfrpc 的方法，确保启动之后，溯光所在服务器可以和 msfrpc 服务正常通信（通过浏览器访问IP+端口号，正常访问即可），其次检查配置文件中的  msf 接口地址和账号密码是否一致。
3.以上都确保检查无误，请通过 package.sh/bat 脚本重新编译项目并运行，否则修改不会生效。

**Comment by just805** [comment]
我已经入坑了，搭建成功了，如果作者不建议的话，我准备出了一个搭建教程，比如awvs 等等一些配置。

**Comment by iSafeBlue** [comment]
当然不介意

**Comment by just805** [comment]
好的，感谢作者的项目。
